apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit
  namespace: default
subjects:
  - kind: Group
    name: backend
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: web
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: dwh
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io
